<?php

/**
 * page-contact.php — Contact page template.
 * Generated by the `build-page` Claude Code skill (which delegated block
 * creation to `make-metablock`). See .claude/skills/build-page/SKILL.md
 * and .claude/skills/make-metablock/SKILL.md.
 *
 * Assign this template to a page with the "Contact" slug, or select it
 * directly via Page Attributes → Template in the block editor.
 *
 * Sections (top to bottom): Hero (reused) → Contact (form + info, new) →
 * Office / Location (new) → FAQ (new).
 */

use TAW\Core\Block\BlockRegistry;

BlockRegistry::queue('hero', 'contact', 'office_location', 'faq');

get_header();
?>

<?php BlockRegistry::render('hero'); ?>
<?php BlockRegistry::render('contact'); ?>
<?php BlockRegistry::render('office_location'); ?>
<?php BlockRegistry::render('faq'); ?>

<?php get_footer();
