<?php

declare(strict_types=1);

/**
 * Generated by the `make-metablock` Claude Code skill (invoked via `build-page`)
 * as part of the Contact page demo. See .claude/skills/make-metablock/SKILL.md
 * and .claude/skills/build-page/SKILL.md.
 *
 * Field structure follows AGENTS.md § "Common Section Catalog" → FAQ verbatim.
 */

namespace TAW\Blocks\Faq;

use TAW\Core\Block\MetaBlock;
use TAW\Core\Metabox\Metabox;

class Faq extends MetaBlock
{
    protected string $id = 'faq';

    protected function registerMetaboxes(): void
    {
        new Metabox([
            'id'      => 'taw_faq',
            'title'   => __('FAQ Section', 'taw-theme'),
            'screens' => ['page'],
            'fields'  => [
                ['id' => 'faq_heading', 'label' => __('Heading', 'taw-theme'), 'type' => 'text', 'width' => '50'],
                [
                    'id'           => 'faq_items',
                    'label'        => __('Questions', 'taw-theme'),
                    'type'         => 'repeater',
                    'button_label' => __('Add Question', 'taw-theme'),
                    'fields'       => [
                        ['id' => 'question', 'label' => __('Question', 'taw-theme'), 'type' => 'text', 'required' => true],
                        ['id' => 'answer',   'label' => __('Answer', 'taw-theme'),   'type' => 'textarea', 'rows' => 4],
                    ],
                ],
            ],
        ]);
    }

    protected function getData(int|false $postId): array
    {
        return [
            'heading' => $this->getMeta($postId, 'faq_heading'),
            'items'   => $this->getRepeater($postId, 'faq_items'),
        ];
    }
}
