<?php

/**
 * FAQ Block Template
 * Generated by the `make-metablock` Claude Code skill (invoked via `build-page`).
 * See .claude/skills/make-metablock/SKILL.md and .claude/skills/build-page/SKILL.md.
 *
 * Available variables (from Faq::getData):
 *
 * @var string $heading
 * @var array  $items
 */

if (empty($heading) && empty($items)) {
    return;
}

?>

<section class="faq py-16">
    <div class="section-container mx-auto max-w-3xl w-[90%]">
        <?php if ($heading) : ?>
            <h2 class="faq__heading text-3xl font-bold mb-8"><?php echo esc_html($heading); ?></h2>
        <?php endif; ?>

        <?php if (!empty($items)) : ?>
            <div class="faq__items flex flex-col divide-y divide-gray-200">
                <?php foreach ($items as $item) : ?>
                    <?php if (empty($item['question'])) continue; ?>
                    <details class="faq__item group py-4">
                        <summary class="faq__question flex items-center justify-between cursor-pointer list-none font-medium text-lg">
                            <?php echo esc_html($item['question']); ?>
                            <span class="faq__icon ml-4 shrink-0 transition-transform group-open:rotate-45" aria-hidden="true">+</span>
                        </summary>
                        <?php if (!empty($item['answer'])) : ?>
                            <div class="faq__answer mt-2 text-gray-600">
                                <?php echo wp_kses_post(wpautop($item['answer'])); ?>
                            </div>
                        <?php endif; ?>
                    </details>
                <?php endforeach; ?>
            </div>
        <?php endif; ?>
    </div>
</section>
