<?php

/**
 * Office / Location Block Template
 * Generated by the `make-metablock` Claude Code skill (invoked via `build-page`).
 * See .claude/skills/make-metablock/SKILL.md and .claude/skills/build-page/SKILL.md.
 *
 * Available variables (from OfficeLocation::getData):
 *
 * @var string $heading
 * @var string $map_url
 * @var array  $hours
 * @var string $address
 */

if (empty($heading) && empty($map_url) && empty($address)) {
    return;
}

?>

<section class="office-location py-16 bg-gray-50">
    <div class="section-container mx-auto max-w-360 w-[90%]">
        <?php if ($heading) : ?>
            <h2 class="office-location__heading text-3xl font-bold mb-8"><?php echo esc_html($heading); ?></h2>
        <?php endif; ?>

        <div class="office-location__grid grid grid-cols-1 md:grid-cols-2 gap-10 items-start">
            <?php if ($map_url) : ?>
                <div class="office-location__map aspect-video w-full overflow-hidden rounded-lg">
                    <iframe
                        src="<?php echo esc_url($map_url); ?>"
                        class="w-full h-full border-0"
                        loading="lazy"
                        referrerpolicy="no-referrer-when-downgrade"
                        title="<?php esc_attr_e('Office location map', 'taw-theme'); ?>"
                    ></iframe>
                </div>
            <?php endif; ?>

            <div class="office-location__details flex flex-col gap-6">
                <?php if ($address) : ?>
                    <div class="office-location__address">
                        <p class="text-sm font-semibold uppercase tracking-wide text-gray-500"><?php esc_html_e('Address', 'taw-theme'); ?></p>
                        <p class="text-lg"><?php echo wp_kses_post($address); ?></p>
                    </div>
                <?php endif; ?>

                <?php if (!empty($hours)) : ?>
                    <div class="office-location__hours">
                        <p class="text-sm font-semibold uppercase tracking-wide text-gray-500 mb-2"><?php esc_html_e('Office Hours', 'taw-theme'); ?></p>
                        <ul class="flex flex-col gap-1">
                            <?php foreach ($hours as $row) : ?>
                                <li class="flex justify-between gap-4 text-base">
                                    <span class="font-medium"><?php echo esc_html($row['days'] ?? ''); ?></span>
                                    <span class="text-gray-600"><?php echo esc_html($row['hours'] ?? ''); ?></span>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    </div>
</section>
