<?php

declare(strict_types=1);

/**
 * Generated by the `make-metablock` Claude Code skill (invoked via `build-page`)
 * as part of the Contact page demo. See .claude/skills/make-metablock/SKILL.md
 * and .claude/skills/build-page/SKILL.md.
 */

namespace TAW\Blocks\OfficeLocation;

use TAW\Core\Block\MetaBlock;
use TAW\Core\Metabox\Metabox;
use TAW\Core\OptionsPage\OptionsPage;

class OfficeLocation extends MetaBlock
{
    protected string $id = 'office_location';

    protected function registerMetaboxes(): void
    {
        new Metabox([
            'id'      => 'taw_office_location',
            'title'   => __('Office / Location Section', 'taw-theme'),
            'screens' => ['page'],
            'fields'  => [
                ['id' => 'office_heading', 'label' => __('Heading', 'taw-theme'), 'type' => 'text', 'width' => '50'],
                ['id' => 'office_map_embed_url', 'label' => __('Map Embed URL', 'taw-theme'), 'type' => 'url', 'width' => '50', 'description' => __('Google Maps "Embed a map" iframe src URL.', 'taw-theme')],
                [
                    'id'           => 'office_hours',
                    'label'        => __('Office Hours', 'taw-theme'),
                    'type'         => 'repeater',
                    'button_label' => __('Add Row', 'taw-theme'),
                    'max'          => 7,
                    'fields'       => [
                        ['id' => 'days',  'label' => __('Day(s)', 'taw-theme'), 'type' => 'text', 'width' => '50', 'placeholder' => __('Mon–Fri', 'taw-theme')],
                        ['id' => 'hours', 'label' => __('Hours', 'taw-theme'),  'type' => 'text', 'width' => '50', 'placeholder' => __('9:00 – 18:00', 'taw-theme')],
                    ],
                ],
            ],
        ]);
    }

    protected function getData(int|false $postId): array
    {
        return [
            'heading' => $this->getMeta($postId, 'office_heading'),
            'map_url' => $this->getMeta($postId, 'office_map_embed_url'),
            'hours'   => $this->getRepeater($postId, 'office_hours'),
            'address' => OptionsPage::get('company_address'),
        ];
    }
}
