<?php

declare(strict_types=1);

/**
 * Generated by the `make-metablock` Claude Code skill (invoked via `build-page`)
 * as part of the Contact page demo. See .claude/skills/make-metablock/SKILL.md
 * and .claude/skills/build-page/SKILL.md.
 */

namespace TAW\Blocks\Contact;

use TAW\Core\Block\MetaBlock;
use TAW\Core\Metabox\Metabox;
use TAW\Core\Form\Form;
use TAW\Core\OptionsPage\OptionsPage;

class Contact extends MetaBlock
{
    protected string $id = 'contact';

    public static function boot(): void
    {
        add_action('init', static function () {
            Form::register([
                'id'           => 'contact',
                'submit_label' => __('Send Message', 'taw-theme'),
                'fields'       => [
                    ['id' => 'name',    'label' => __('Name', 'taw-theme'),    'type' => 'text',     'required' => true, 'width' => 50],
                    ['id' => 'email',   'label' => __('Email', 'taw-theme'),   'type' => 'email',    'required' => true, 'width' => 50],
                    ['id' => 'subject', 'label' => __('Subject', 'taw-theme'), 'type' => 'text',     'required' => true],
                    ['id' => 'message', 'label' => __('Message', 'taw-theme'), 'type' => 'textarea', 'required' => true],
                ],
            ]);
        });
    }

    protected function registerMetaboxes(): void
    {
        new Metabox([
            'id'     => 'taw_contact',
            'title'  => __('Contact Section', 'taw-theme'),
            'screens' => ['page'],
            'fields' => [
                ['id' => 'contact_heading',    'label' => __('Heading', 'taw-theme'),    'type' => 'text', 'required' => true, 'width' => '50'],
                ['id' => 'contact_subheading', 'label' => __('Subheading', 'taw-theme'), 'type' => 'text', 'width' => '50'],
            ],
        ]);
    }

    protected function getData(int|false $postId): array
    {
        return [
            'heading'    => $this->getMeta($postId, 'contact_heading'),
            'subheading' => $this->getMeta($postId, 'contact_subheading'),
            'phone'      => OptionsPage::get('company_phone'),
            'email'      => OptionsPage::get('company_email'),
            'address'    => OptionsPage::get('company_address'),
        ];
    }
}
