<?php

/**
 * Contact Block Template
 * Generated by the `make-metablock` Claude Code skill (invoked via `build-page`).
 * See .claude/skills/make-metablock/SKILL.md and .claude/skills/build-page/SKILL.md.
 *
 * Available variables (from Contact::getData):
 *
 * @var string $heading
 * @var string $subheading
 * @var string $phone
 * @var string $email
 * @var string $address
 */

use TAW\Core\Form\Form;

if (empty($heading)) {
    return;
}

?>

<section class="contact py-16">
    <div class="section-container mx-auto max-w-360 w-[90%]">
        <div class="contact__intro max-w-2xl mb-10">
            <h2 class="contact__heading text-3xl font-bold"><?php echo esc_html($heading); ?></h2>
            <?php if ($subheading) : ?>
                <p class="contact__subheading mt-2 text-lg text-gray-600"><?php echo esc_html($subheading); ?></p>
            <?php endif; ?>
        </div>

        <div class="contact__grid grid grid-cols-1 md:grid-cols-3 gap-10">
            <div class="contact__form md:col-span-2">
                <?php Form::display('contact'); ?>
            </div>

            <div class="contact__info flex flex-col gap-4">
                <?php if ($phone) : ?>
                    <div class="contact__info-item">
                        <p class="text-sm font-semibold uppercase tracking-wide text-gray-500"><?php esc_html_e('Phone', 'taw-theme'); ?></p>
                        <a class="text-lg" href="tel:<?php echo esc_attr($phone); ?>"><?php echo esc_html($phone); ?></a>
                    </div>
                <?php endif; ?>

                <?php if ($email) : ?>
                    <div class="contact__info-item">
                        <p class="text-sm font-semibold uppercase tracking-wide text-gray-500"><?php esc_html_e('Email', 'taw-theme'); ?></p>
                        <a class="text-lg" href="mailto:<?php echo esc_attr($email); ?>"><?php echo esc_html($email); ?></a>
                    </div>
                <?php endif; ?>

                <?php if ($address) : ?>
                    <div class="contact__info-item">
                        <p class="text-sm font-semibold uppercase tracking-wide text-gray-500"><?php esc_html_e('Address', 'taw-theme'); ?></p>
                        <p class="text-lg"><?php echo wp_kses_post($address); ?></p>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    </div>
</section>
